### ISSUE TITLE
Options?

### ISSUE THREAD

**Issue by YoungPup** [mannynotfound/yeezy-copper#1]
Hey, super excited that I found this, but where are the options? How does the bot know what size I need? And how does it start working?

**Comment by YoungPup** [comment]
Also, how does the bot know any of my info?

**Comment by YoungPup** [comment]
Ok, so I saw where to edit the info and stuff. You said once it goes on a sneaker page, it should start working. Well I'm on this page http://www.adidas.com/us/superstar-foundation-shoes/S81858.html?pr=CUSTOMIZE_IMG_Superstar%2520Foundation%2520Shoes and it's not doing anything, and I've clicked on the extension multiple times.

**Comment by mannynotfound** [comment]
@YoungPup I definitely tested using the Superstars pages a few times. Can you open the Developer Console (View > Developer > JavaScript Console) and see if any messages are being logged, and if so which ones

**Comment by YoungPup** [comment]
It says 
"Uncaught  SyntaxError: Unexpected token ILLEGAL             yeezyCoper.js:2"

**Comment by mannynotfound** [comment]
@YoungPup Looks like you have a syntax error on line 2 somewhere. I just tested the Superstars page on a clean install of this repository and it was working. At some point you broke the config object. Recommend having some bare JS knowledge before using this thing :)

**Comment by YoungPup** [comment]
Ok, my brother knows a decent amount about coding and stuff. I’ll have him take a look at it. Thanks :)
