### ISSUE TITLE
Auto executing script for limited releases

### ISSUE THREAD

**Issue by vaMuchenje** [mannynotfound/yeezy-copper#11]
So what is the walkthrough for using this script? Can i use it to buy the limited editions that have specific release dates and times? Like Yeezy Boosts. Once I install it, do I have to wait for the release time and then click the icon/ open the page? Usually the shoes sell out within seconds, so is there a way to automate it checking for the release and/or availability of the page?

**Comment by aklingspor** [comment]
@vaMuchenje 
- Yes, you can use it to purchase Yeezy branded Adidas shoes with an Adidas product page -- all shoes sold on Adidas.com can be purchased using this extension.
- Whenever the shoes you'd like to purchase are released, all you have to do is access the product page URL in Chrome, and then the bot will take care of the rest, assuming you have it configured properly.
- Most limited-edition shoes (like the Boosts you were referring to) are sold out extremely quickly, so this extension will increase your chances tremendously. 
- Currently the bot does not automatically check for new releases; However, I'm hoping to push a new version soon that helps users locate popular new releases and aid in automating that process.

The main walkthrough can also be found at [YeezyCopper's site](yeezycopper.com).
