### ISSUE TITLE
How to use it on adidas.de? The same way?

### ISSUE THREAD

**Issue by lapa1016** [mannynotfound/yeezy-copper#12]
Hi,

how can i use this on adidas.de? Can i use it the same way?
How can i try it with an other pair of shoes? The copper only checks page if im on adidas.de/yeezy.

Thank you.

**Comment by michielmetcake** [comment]
Same question

**Comment by aklingspor** [comment]
This extension is not designed to be used with any websites other than the US version of Adidas (http://adidas.com). Based on user reports, the extension cannot read other versions of the Adidas website yet. 

An update may be coming soon, please be patient.
