### ISSUE TITLE
How do I make this into a Supreme bot ?

### ISSUE THREAD

**Issue by vhad500** [mannynotfound/yeezy-copper#5]
Hi, I just came across your repo and was amazed at your yeezy bot. I know Java and Python but not javascript so do I change the config in yeeze-copper.js to turn it into a supreme bot ?

**Comment by mannynotfound** [comment]
@vhad500 unfortunately this code only works for adidas.com . you would have to rewrite most of it to work for another store.

**Comment by landforce** [comment]
@artnotfound yeah yea yeah ya i get it but what about converting it to a supreme bot tho fam pls convert teh codez
